# Default values for fridgetoplate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: rozozepine
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

kafka:
  zookeeper:
    persistence:
      enabled: false
  persistence:
    enabled: false

frigo-db:
  driver_name: org.postgresql
  persistence:
     enabled: false
  postgresUser: frig
  postgresDatabase: frigodb
  postgresqlDatabase: frigodb
  global:
      persistence:
         enabled: false
      postgresqlDatabase: frigodb

rbac:
  create: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
podSecurityContext: {}
securityContext: {}


