language: java

services:
    - docker

addons:
  ssh_known_hosts: defosse0@129.194.69.128
  sonarcloud:
    organization: pinfo-2020
    token:
      secure: ILuluYoJgzPAS/vzxJVQAYNwH/7Ji9nfz1xlui3MnS00ey3wQRQGHIzvpm1dNs4F3h7Ae15Jy8pUc1DmW98WbaPSQ1LahHg0reUQsaodFPHq2C2pM3w8zmen/GuPRo9EBYNoH2wg8yajzIRLIrg94QEnXNozc36NNKiSl5Bz2NYRSk1oumxjaJTOr6aPal9psSC65lWzM3KYA+NnjNQy0Pwm6y8ANm+hVaYC485KBQzahdo4VZMboY4HBGjnclxPFDc14B/sG2K6zNhh4XqqcnIx3u+CiJUtrUr7jKK74+yLlvTVP56dW5DqZzUhcoKw0X2aDLT+i1w6ssBqinyDqjrAef5dnf9u8wB7f9aZ7Vm747EAopVG+wo4qFG8BlB2kutmC8AlXvFCnUJ3u6dovW7uNKp4XaNzajAExKqp5yiCmJgVQprbT1+lhHFl0HqgBCo7ckyp++K6NS9vaIwrPWifZ+Xj8OxdbZAfdqkM+RgayH/EIZR2GmYvt5SrNtmhInO1rGk3j6PmaHS6/MbqgQkYrp7KaS9mFFMJqF+3S7TXEGeifLyqeoOgWDZ42e3h4W4yEklYrNjIiXOR9i8v7esm6K+473WCtdsiRxVBehETQriB6LDBEp+rNuQOlrtYt7CHwtf6WrGXATGGsOAQIWfrfuyD/aTYAb0KoWetls0=
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- curl -L https://git.io/get_helm.sh | bash
- helm init --client-only

script:
- mvn test
- mvn sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-1 -Dsonar.organization=pinfo-2020
  -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=860546795f4339575e9a105a89a565f45b305bc1
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.test.skip=true -Ppackage-docker-image
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker tag feedfusion/api-insta rozozepine/api-insta:latest
- docker tag feedfusion/api-twitter rozozepine/api-twitter:latest
- docker tag feedfusion/api-facebook rozozepine/api-facebook:latest
- docker tag feedfusion/api-gateway rozozepine/api-gateway:latest
- docker push rozozepine/api-insta:latest
- docker push rozozepine/api-twitter:latest
- docker push rozozepine/api-facebook:latest
- docker push rozozepine/api-gateway:latest
- helm package helm-chart/feedfusion/ -d docs/
- helm repo index docs/

deploy:
  - provider: script
    skip_cleanup: true
    script: ssh defosse0@129.194.69.128 'bash deploy_script.sh' 
    on:
        branch: master

  - provider: script
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: docs
    on:
        branch: master
