language: java

services:
    - docker

addons:
    sonarcloud:
        organization: "pinfo-2020"
        token:
            secure: "tNOtFGjNRYqLH3oSfWt7vhOZ6+onUZ6JWlUDGN6LrG3Wl66i1/achxMwkVwPg8RPwD0H8IQ+fZcmYS9lvXeClbT5a5HJlhwqLwe2ZG0TMQReW/eqbG6xHMcbIMMywSSmJqHngjjBSEtsXeEkk8FoUME30lePZfc45csyDAPJ52IwRS4lJCKgVkZk81gKsQ5he1krY2hYOUiuqp0IeHSFRAMhQSO01WKCDNm7B1S2Mi0YsrWk6OPAYjOPKO5kRwoP2cuHkyrA6RPsRv1NW/h++3dzqMeIK0bpbA/0YTXsNtBTrmC3kR87lJn6+e7ha4iLuXXwBsV0PJ7Djn9F2H0edSHFy7nBPeJduiIXUr0L7wpWoxdBVzwuf88X6et6kTLe0QKWaHYspM2sN9ftcIEfBy07PLJn8C8XuQAKu5t5YQQArPAYbFs+O7tbI2afu3c2GyFLNgfs9kxSx5BerLa1eF0oUOSq0KxYzNjipC3WQDYisjqEtZ+Ed2S5DnLdaa790FBxL4uZhHvW/IFKZDFLc2iiqY3dLkOfBxhAc4dYbsFls6L+rzJeK2VbHb4HU2cdPyr/vD1PgAfJBtkl05b4arabHhD3kyjvJSuJbOuD6aEY1XflNE/cVIYB8zNcPXFTp/wrBYX2W4wh/19cTubmxqWBORUSBAiMaMN5HSV61lg="
      
cache:
    directories:
        - .autoconf
        - $HOME/.m2

script:
    - mvn test
    - mvn sonar:sonar -Dsonar.projectKey=pinfo-2020_pinfo-1 -Dsonar.organization=pinfo-2020 -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=be934dd83d6eb7ae35fc7c9b7bdb06ed76bebdbe
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.test.skip=true -Ppackage-docker-image 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
    - docker tag feedfusion/api-insta rozozepine/api-insta:latest
    - docker tag feedfusion/api-twitter rozozepine/api-twitter:latest
    - docker tag feedfusion/api-facebook rozozepine/api-facebook:latest
    - docker tag feedfusion/api-gateway rozozepine/api-gateway:latest
    - docker push rozozepine/api-insta:latest
    - docker push rozozepine/api-twitter:latest
    - docker push rozozepine/api-facebook:latest
    - docker push rozozepine/api-gateway:latest
  