version: "3.5"

services:

  ingredient-database:
    image: postgres:10
    container_name: ingredient-database
    hostname: ingredient-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: ingredient
      POSTGRES_PASSWORD: ing
      POSTGRES_DB: ingredient
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ingredient", "-d", "ingredient"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata-frige:/var/lib/postgresql/data
      - ../../config/data/ingredient_data.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    stdin_open: true
    tty: true

  ingredient-service:
    container_name: ingredient-service    
    image:  pickncook/ingredient_service:latest
    hostname: ingredient-service
    environment:
      THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST: "kafka"
      THORNTAIL_KAFKA_DASH_CONFIGURATION_PORT: "9092"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_INGREDIENTDS_CONNECTION_DASH_URL: "jdbc:postgresql://ingredient-database:5432/ingredient"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_INGREDIENTDS_DRIVER_DASH_NAME: 'postgresql'   
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_INGREDIENTDS_USER_DASH_NAME: 'ingredient'
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_INGREDIENTDS_PASSWORD: 'ing'
    networks:
      - backend-network   
    ports:
      - "10080:28080"
    depends_on:
       - ingredient-database
volumes:
   pgdata-frige:

  

networks:
    backend-network:
      external:
        name: backend-network