apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pickncook.fullname" . }}-web-ui-config
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "pickncook.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "config/app-config.json").AsConfig | indent 2 }}
---