apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pickncook.fullname" . }}.recipe-service
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "pickncook.labels" . | nindent 4 }}
    {{- include "pickncook.labels" . | nindent 4 }}.recipe-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pickncook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "pickncook.fullname" . }}.recipe-service
        {{- include "pickncook.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "pickncook.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
         - name: check-db-ready
           image: postgres:12.1-alpine
           command: ['sh', '-c', 
             'until pg_isready -h {{ .Release.Name }}-recipe-db -p 5432; 
             do echo waiting for database; sleep 2; done;']                   
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}recipe_service:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST
              value: "{{ .Release.Name }}-kafka"
            - name: THORNTAIL_KAFKA_DASH_CONFIGURATION_POST
              value: "9092"
            - name: THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_recipeDS_CONNECTION_DASH_URL
              value: "jdbc:postgresql://{{ .Release.Name }}-recipe-db:5432/recipe"
            - name: THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_recipeDS_DRIVER_DASH_NAME
              value: "postgresql"   
            - name: THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_recipeDS_USER_DASH_NAME
              value: "recipe"
            - name: THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_recipeDS_PASSWORD
              value: "recipe"              
          ports:
            - name: http
              containerPort: 28080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}