apiVersion: v1
kind: Service
metadata:
  name: {{ include "pickncook.fullname" . }}-web-ui
  labels:
    {{- include "pickncook.labels" . | nindent 4 }}.web-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
      app: {{ include "pickncook.fullname" . }}.web-ui
