apiVersion: v1
name: pickncook
description: A Helm chart for Kubernetes
type: application

version: 0.1.0
appVersion: 1.16.0

dependencies:
    - name: nginx-ingress 
      version: 1.27.0
      repository: https://kubernetes-charts.storage.googleapis.com  
    - name: keycloak
      version: 7.4.0
      repository: https://codecentric.github.io/helm-charts
    - name: postgresql
      version: 7.7.2
      repository: https://kubernetes-charts.storage.googleapis.com
      alias: ingredient-db
    - name: postgresql
      version: 7.7.2
      repository: https://kubernetes-charts.storage.googleapis.com
      alias: recipe-db
    - name: postgresql
      version: 7.7.2
      repository: https://kubernetes-charts.storage.googleapis.com
      alias: fridge-db
    - name: kafka 
      version: 7.2.9
      repository: https://charts.bitnami.com/bitnami   