# Default values for pickncook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: rozozepine/
  tag: 
  pullPolicy: Always

#imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

kafka:
  zookeeper:
    persistence:
      enabled: false
  persistence:
    enabled: false

rbac:
  create: true

service:
  type: ClusterIP
  port: 80

keycloak:
  keycloak:
    password: asdfghjkl
    extraVolumes: |
      - name: keycloak-realm-secret
        secret:
          secretName: keycloak-realm-secret
    extraVolumeMounts: |
      - name: keycloak-realm-secret
        mountPath: "/realm/"
        readOnly: true          
    extraArgs: -Dkeycloak.import=/realm/realms.json
    livenessProbe: |
      initialDelaySeconds: 120
    readinessProbe: |
      initialDelaySeconds: 120

ingress:
  enabled: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
podSecurityContext: {}
securityContext: {}


