apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "fridgetoplate.fullname" . }}.ingress-static
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "fridgetoplate.labels" . | nindent 4 }}
    {{- include "fridgetoplate.labels" . | nindent 4 }}.ingress
spec:
  rules:
    - http:
      paths:
        - path: /
        backend:
          serviceName: {{ include "fridgetoplate.fullname" . }}-web-ui
          servicePort: 80
---