apiVersion: v1
kind: Service
metadata:
  name: {{ include "fridgetoplate.fullname" . }}-web-ui
  labels:
    {{- include "fridgetoplate.labels" . | nindent 4 }}.web-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
      app: {{ include "fridgetoplate.fullname" . }}-web-ui
